name: Tests
on: push

jobs:
  # <---------------- TEST BASIC CONFIG ------------------>
  basic-success:
    name: Basic (SHOULD FAIL)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Basic Test
        uses: ./
        with:
         image: alpine:latest
         accept-extensions: pem
         report-name: basic-fail

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Basic Fail Report
          path: basic-fail.json

  basic-pass:
    name: Basic (SHOULD SUCCEED)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Basic Test
        uses: ./
        with:
         image: alpine:latest
         accept-extensions: pem
         exit-code: 0
         report-name: basic-success

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Basic Success Report
          path: dockle-success-report.json

  # <--------------- TEST ADVANCED CONFIG ---------------->
  advanced:
    name: Advanced
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Advanced Test
        uses: ./
        with:
          image: alpine:latest
          report-format: sarif
          report-name: dockle
          failure-threshold: fatal
          exit-code: 0
          dockle-version: 0.4.13
          accept-extensions: pem

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: SARIF Report
          path: dockle.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: dockle.sarif
